version: "3"
services:
    amazonlinux_webapp_dev:
        #build:
        #    context: .
        #    dockerfile: WebappDockerfile
        # image: amazonlinux
        container_name: amazonlinux-webapp-dev
        stdin_open: true
        tty: true
        restart: always
        environment:
            - DEPLOY_ENV=DEV
            - PYTHONPATH=/amazonlinux_webapp
            - TZ=Asia/Singapore
        volumes:
            - ../.:/aws_content_analysis
            - .:/tmp/dockers
        working_dir: /aws_content_analysis/source/webapp
        ulimits:
            nofile:
                soft: "999999"
                hard: "999999"
        ports:
          - "8080:8080"
        networks:
            - backend_network
        entrypoint: sh -c "echo 'Starting DEV npm web server'; cd /aws_content_analysis/source/webapp; npm install; npm run serve"
    
networks:
    backend_network:
        driver: bridge